Upgrade to latest 4.x TypeScript
This fixes an error reported by tsc:

node_modules/@types/node/events.d.ts:109:43 - error TS2370: A rest parameter must be of an array type.
109                 T[K] extends unknown[] ? (...args: T[K]) => void : never